-- Hangat MariaDB migration rollback guide
--
-- DO NOT RUN THIS FILE AS-IS.
-- MariaDB DDL causes implicit commits. A complete automatic rollback cannot be
-- guaranteed after new application data or dependent rows exist.
-- Restore a verified pre-migration backup whenever possible.
--
-- Every destructive reverse statement below is intentionally commented out.
-- Before selectively enabling one:
--   1. stop the application;
--   2. take another backup;
--   3. inspect all dependent rows and FK names;
--   4. prove that unsigned-to-signed/type narrowing is safe;
--   5. run 20260828_verify.sql after each phase.

-- ---------------------------------------------------------------------------
-- A. Seed reversal (safe only while no production row references the seeds)
-- ---------------------------------------------------------------------------
-- DELETE FROM place_categories
-- WHERE code IN ('TOURIST', 'CAFE', 'FOOD', 'LODGING');
-- DELETE FROM regions
-- WHERE code IN ('EAST', 'WEST', 'SOUTH', 'NORTH');
-- DELETE FROM data_sources WHERE code IN ('KTO', 'KAKAO_LOCAL');

-- ---------------------------------------------------------------------------
-- B. Drop newly added explicit FKs before reversing types
-- ---------------------------------------------------------------------------
-- ALTER TABLE course_items
--     DROP FOREIGN KEY fk_course_items_replaced_from_place,
--     DROP FOREIGN KEY fk_course_items_place,
--     DROP FOREIGN KEY fk_course_items_course;
-- ALTER TABLE place_source_mappings
--     DROP FOREIGN KEY fk_place_source_mappings_source,
--     DROP FOREIGN KEY fk_place_source_mappings_place;
-- ALTER TABLE places
--     DROP FOREIGN KEY fk_places_primary_category,
--     DROP FOREIGN KEY fk_places_region;
-- ALTER TABLE courses DROP FOREIGN KEY fk_courses_parent;

-- ---------------------------------------------------------------------------
-- C. Remove nullable columns introduced by the migration
-- DESTRUCTIVE: values stored after migration will be lost.
-- ---------------------------------------------------------------------------
-- ALTER TABLE course_items DROP COLUMN recommendation_score;
-- ALTER TABLE courses DROP COLUMN parent_course_id;
-- ALTER TABLE places
--     DROP COLUMN hidden_gem_calculated_at,
--     DROP COLUMN hidden_gem_algorithm_version,
--     DROP COLUMN hidden_gem_score,
--     DROP COLUMN good_price_base_date;

-- ---------------------------------------------------------------------------
-- D. Restore the former signed/Hibernate-generated column shapes
-- Only valid for the confirmed empty pre-migration tables. Validate ranges first.
-- ---------------------------------------------------------------------------
-- ALTER TABLE regions
--     MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
--     MODIFY kma_grid_x INT NULL,
--     MODIFY kma_grid_y INT NULL,
--     MODIFY display_order INT NOT NULL,
--     MODIFY is_active BIT(1) NOT NULL,
--     MODIFY created_at DATETIME(6) NOT NULL,
--     MODIFY updated_at DATETIME(6) NOT NULL;
--
-- ALTER TABLE place_categories
--     MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
--     MODIFY display_order INT NOT NULL,
--     MODIFY is_active BIT(1) NOT NULL,
--     MODIFY created_at DATETIME(6) NOT NULL,
--     MODIFY updated_at DATETIME(6) NOT NULL;
--
-- ALTER TABLE places
--     MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
--     MODIFY region_id BIGINT NOT NULL,
--     MODIFY primary_category_id BIGINT NOT NULL,
--     MODIFY business_status ENUM('CLOSED','OPEN','TEMP_CLOSED','UNKNOWN') NOT NULL,
--     MODIFY is_good_price BIT(1) NOT NULL,
--     MODIFY is_hidden_gem BIT(1) NOT NULL,
--     MODIFY review_count INT NOT NULL,
--     MODIFY created_at DATETIME(6) NOT NULL,
--     MODIFY updated_at DATETIME(6) NOT NULL;
--
-- ALTER TABLE place_source_mappings
--     MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
--     MODIFY place_id BIGINT NOT NULL,
--     MODIFY data_hash VARCHAR(64) NULL,
--     MODIFY is_active BIT(1) NOT NULL,
--     MODIFY created_at DATETIME(6) NOT NULL,
--     MODIFY updated_at DATETIME(6) NOT NULL;
--
-- ALTER TABLE courses
--     MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
--     MODIFY user_id BIGINT NULL,
--     MODIFY preset_id BIGINT NULL,
--     MODIFY people INT NOT NULL,
--     MODIFY budget_total INT NOT NULL,
--     MODIFY input_fingerprint VARCHAR(64) NULL,
--     MODIFY estimated_cost_min INT NULL,
--     MODIFY estimated_cost_max INT NULL,
--     MODIFY created_at DATETIME(6) NOT NULL,
--     MODIFY updated_at DATETIME(6) NOT NULL;
--
-- ALTER TABLE course_items
--     MODIFY id BIGINT NOT NULL AUTO_INCREMENT,
--     MODIFY course_id BIGINT NOT NULL,
--     MODIFY place_id BIGINT NOT NULL,
--     MODIFY day_no INT NOT NULL,
--     MODIFY position INT NOT NULL,
--     MODIFY start_time TIME(6) NULL,
--     MODIFY end_time TIME(6) NULL,
--     MODIFY inbound_distance_m INT NULL,
--     MODIFY inbound_travel_minutes INT NULL,
--     MODIFY planned_congestion_forecast_id BIGINT NULL,
--     MODIFY planned_weather_forecast_id BIGINT NULL,
--     MODIFY replaced_from_place_id BIGINT NULL,
--     MODIFY created_at DATETIME(6) NOT NULL,
--     MODIFY updated_at DATETIME(6) NOT NULL;

-- ---------------------------------------------------------------------------
-- E. Legacy timestamp phase reversal
-- This migration never drops create_date/update_date. To restore their former
-- NOT NULL state, first backfill every NULL using created_at/updated_at.
-- ---------------------------------------------------------------------------
-- UPDATE courses
-- SET create_date = COALESCE(create_date, created_at),
--     update_date = COALESCE(update_date, updated_at)
-- WHERE create_date IS NULL OR update_date IS NULL;
-- ALTER TABLE courses
--     MODIFY create_date DATETIME(6) NOT NULL,
--     MODIFY update_date DATETIME(6) NOT NULL;

-- ---------------------------------------------------------------------------
-- F. data_sources removal
-- DESTRUCTIVE and only possible after its dependent FK and rows are removed.
-- ---------------------------------------------------------------------------
-- DROP TABLE data_sources;

-- Preferred rollback: restore the verified backup instead of selectively
-- executing the destructive statements above.
