const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const {join}=require('node:path');
const {tmpdir}=require('node:os');
const jsQR=require('jsqr');
const url=(process.env.SAVED_COURSES_TEST_URL || 'http://127.0.0.1:5208')+'/tests/browser/course-share.html';
async function openFirstShare(page){
 await page.locator('.library-card').first().getByRole('button',{name:/ 메뉴$/}).click();
 await page.getByRole('menuitem',{name:'공유',exact:true}).click();
}
const item={id:1,place_id:11,place_name:'금오름',category_name:'오름',region_name:'서부',place_business_status:null,image_url:null,latitude:33.35,longitude:126.3,position:1,start_time:'10:00:00',end_time:'11:20:00',inbound_distance_m:null,inbound_travel_minutes:null,congestion_rate:null,congestion_level:null,congestion_label:null,weather:null};
const course={title:'서부 힐링 코스',start_date:'2026-09-20',end_date:'2026-09-21',transport:'RENTAL_CAR',days:[{day_no:1,visit_date:'2026-09-20',items:[item,{...item,id:2,place_id:22,place_name:'목장',position:2,longitude:126.32,inbound_travel_minutes:15,inbound_distance_m:3200,congestion_level:'QUIET',congestion_rate:24,congestion_label:'한산'}]},{day_no:2,visit_date:'2026-09-21',items:[{...item,id:3,place_name:'둘째 날 장소'}]}]};
(async()=>{
 const browser=await chromium.launch({headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const requests=[]; let active=false, version=0;
 await page.route('**/courses/12/share',async route=>{const method=route.request().method();requests.push(method);if(method==='POST'){active=true;version++}if(method==='DELETE')active=false;await route.fulfill({json:{success:true,result:{active,token:active?'token-'+version:null}}})});
 await page.route('**/shared-courses/*',async route=>{const token=route.request().url().split('/').pop();assert.equal(route.request().headers().authorization,undefined);if(token==='slow')await new Promise(r=>setTimeout(r,350));await route.fulfill(token==='revoked'?{status:404,json:{success:false,code:3310,message:'unavailable'}}:{json:{success:true,result:{...course,title:token==='slow'?'OLD':course.title}}})});
 await page.goto(url);
 await openFirstShare(page);
 await page.getByRole('button',{name:'공유 링크 만들기',exact:true}).waitFor();
 assert.deepEqual(requests,['GET'],'opening must never POST');
 assert.notEqual(await page.locator('.create-share').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)','create CTA needs a visible background');
 assert.equal(await page.locator('.course-share-dialog').evaluate(el=>el.open),true);
 await page.keyboard.press('Escape');assert.equal(await page.locator('.course-share-dialog').count(),0);
 assert.equal(await page.locator('.library-card').first().getByRole('button',{name:/ 메뉴$/}).evaluate(el=>el===document.activeElement),true);
 await openFirstShare(page);
 await page.getByRole('button',{name:'공유 링크 만들기',exact:true}).click();
 await page.getByLabel('공유 링크',{exact:true}).waitFor();
 await page.getByRole('button',{name:'QR 코드',exact:true}).click({timeout:3000});
 await page.getByRole('img',{name:'코스 공유 링크 QR 코드'}).waitFor();
 assert.match(await page.getByRole('img',{name:'코스 공유 링크 QR 코드'}).getAttribute('src'),/^data:image\/png/,'QR must be generated locally');
 await page.getByRole('img',{name:'코스 공유 링크 QR 코드'}).screenshot({path:join(tmpdir(),'course-share-qr.png')});
 const pixels=await page.getByRole('img',{name:'코스 공유 링크 QR 코드'}).evaluate(img=>{
   const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;
   const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);return {width:canvas.width,height:canvas.height,data:Array.from(ctx.getImageData(0,0,canvas.width,canvas.height).data)};
 });
 assert.equal(jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height)?.data,await page.getByLabel('공유 링크',{exact:true}).inputValue(),'scanning QR must open the current share URL');
 await page.getByRole('button',{name:'QR 코드',exact:true}).click();
 assert.match(await page.getByLabel('공유 링크',{exact:true}).inputValue(),/\/share\/token-1$/);
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'링크 복사',exact:true}).click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/\/share\/token-1$/);
 await page.getByRole('button',{name:'카카오톡 공유',exact:true}).click();
 assert.equal((await page.evaluate(()=>window.qaSends))[0].buttonTitle,'코스 보기');
 await page.getByRole('button',{name:'공유 중지',exact:true}).click();await page.getByRole('button',{name:'취소',exact:true}).click();
 assert.equal(requests.filter(x=>x==='DELETE').length,0);
 await page.getByRole('button',{name:'공유 중지',exact:true}).click();await page.getByRole('button',{name:'공유 중지 확인',exact:true}).click();
 await page.getByRole('button',{name:'공유 링크 만들기',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#course-share-url')?.value.endsWith('token-2'));
 assert.equal(await page.getByRole('img',{name:'코스 공유 링크 QR 코드'}).count(),0,'old QR must not survive token rotation');
 await page.screenshot({path:join(tmpdir(),'course-share-dialog.png')});await page.keyboard.press('Escape');
 await page.evaluate(()=>window.qaGo('/share/token-2'));await page.getByRole('heading',{name:'서부 힐링 코스',exact:true}).waitFor();
 assert.equal(await page.locator('.place-stop').count(),2);
 assert.equal(await page.locator('.browser-tabs,.tab-toolbar').count(),0,'public page must have no owner tabs or edit/share actions');
 assert.equal(await page.locator('.place-stop .crowd-pill').count(),1,'known crowd level has a separate compact badge');
 assert.match(await page.locator('.place-stop').first().innerText(),/혼잡 예보 없음/);assert.match(await page.locator('.place-stop').first().innerText(),/체류 1시간 20분/);
 assert.equal(await page.locator('.place-detail').first().getAttribute('href'),'/places/11');
 assert.equal(await page.locator('meta[name=referrer]').getAttribute('content'),'no-referrer');assert.match(await page.locator('meta[name=robots]').getAttribute('content'),/noindex/);
 const mapCanvas=await page.locator('.shared-map .kakao-map').boundingBox();
 assert.ok(mapCanvas.height>=570,'Kakao canvas must fill the desktop map panel, not collapse to marker height');
 await page.screenshot({path:join(tmpdir(),'course-share-desktop.png')});
 await page.getByRole('button',{name:/DAY 2/}).click();assert.match(await page.locator('.place-stop').innerText(),/둘째 날 장소/);
 await page.evaluate(()=>window.qaGo('/share/slow'));await page.waitForTimeout(40);await page.evaluate(()=>window.qaGo('/share/token-2'));await page.waitForTimeout(500);assert.equal(await page.locator('h1').innerText(),'서부 힐링 코스');
 await page.setViewportSize({width:390,height:844});
 const handle=page.getByRole('button',{name:'공유 일정 패널 크기 조절',exact:true});
 const panelBefore=await page.locator('.shared-itinerary').boundingBox();
 await handle.focus();await page.keyboard.press('ArrowUp');
 assert.ok((await page.locator('.shared-itinerary').boundingBox()).height>panelBefore.height,'keyboard expands mobile sheet');
 await page.keyboard.press('ArrowDown');
 const handleBox=await handle.boundingBox();
 await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2);await page.mouse.down();await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2-100,{steps:8});await page.mouse.up();
 assert.ok((await page.locator('.shared-itinerary').boundingBox()).height>panelBefore.height+50,'dragging the handle expands the sheet');
 await handle.press('Home');await handle.click();
 assert.ok((await page.locator('.shared-map .kakao-map').boundingBox()).height>=290,'mobile map canvas must fill its panel');
 await page.screenshot({path:join(tmpdir(),'course-share-mobile.png')});
 await page.setViewportSize({width:320,height:640});assert.ok(await page.locator('.shared-course').evaluate(el=>el.scrollWidth<=el.clientWidth),'shared content must fit narrow mobile');
 await page.evaluate(()=>window.qaGo('/share/revoked'));await page.getByRole('heading',{name:'이 공유 코스를 볼 수 없어요.'}).waitFor();assert.equal(await page.locator('.place-stop').count(),0);
 await page.evaluate(()=>window.qaGo('/courses'));assert.equal(await page.locator('meta[name=referrer]').count(),0);
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const mobile=await mobileContext.newPage();await mobile.goto(url+'?preview=1');
 await mobile.getByRole('button',{name:'공유받은 화면',exact:true}).click();
 await mobile.getByRole('heading',{name:'서부 힐링 코스',exact:true}).waitFor();
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'touch mobile page must fit viewport');
 assert.ok((await mobile.locator('.shared-map .kakao-map').boundingBox()).height>=290);
 await mobile.screenshot({path:join(tmpdir(),'course-share-preview-mobile.png')});
 await mobile.setViewportSize({width:320,height:640});
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px touch mobile must fit viewport');
 await mobile.getByRole('button',{name:'저장 코스 목록',exact:true}).click();
 await openFirstShare(mobile);
 await mobile.getByRole('button',{name:'QR 코드',exact:true}).click();
 await mobile.getByRole('img',{name:'코스 공유 링크 QR 코드'}).waitFor();
 assert.ok(await mobile.locator('.course-share-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),'QR modal must fit narrow mobile');
 await mobile.screenshot({path:join(tmpdir(),'course-share-dialog-mobile.png')});
 await mobileContext.close();
 // Exercise the real application route/layout too, not only the isolated fixture.
 const actual=await browser.newPage({viewport:{width:1280,height:900}});
 await actual.addInitScript(()=>{window.kakao={maps:{load:fn=>fn(),LatLng:class{},LatLngBounds:class{extend(){}},Map:class{constructor(el){this.el=el}setCenter(){}panTo(){}setBounds(){}setLevel(){}relayout(){}},CustomOverlay:class{constructor(o){this.content=o.content;o.map.el.append(o.content)}setMap(m){if(!m)this.content.remove()}},Polyline:class{setMap(){}}}}});
 await actual.route('**/shared-courses/*',r=>r.fulfill({json:{success:true,code:2000,result:course}}));
 await actual.route('**/auth/reissue',r=>r.fulfill({status:401,json:{success:false,code:3002,message:'test guest'}}));
 await actual.goto((process.env.SAVED_COURSES_TEST_URL || 'http://127.0.0.1:5208')+'/share/test-public-token');
 await actual.getByRole('heading',{name:'서부 힐링 코스',exact:true}).waitFor();
 await actual.locator('.kakao-marker').first().waitFor();
 assert.equal(await actual.locator('.kakao-marker').first().evaluate(el=>getComputedStyle(el).display),'flex','real shared route must load scoped map marker styles');
 await actual.close();
 console.log('Course sharing owner/public/revoked/race/mobile checks passed');
 } finally { await browser.close() }
})().catch(e=>{console.error(e);process.exit(1)});
