// Run with a local Vite server; PLAYWRIGHT_MODULE optionally points to a shared installation.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const {join}=require('node:path');
const {tmpdir}=require('node:os');
const url=(process.env.SAVED_COURSES_TEST_URL || 'http://127.0.0.1:5208')+'/tests/browser/saved-courses.html';
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.goto(url);
 await page.locator('.library-list .course-tab').first().waitFor();
 assert.equal(await page.locator('.library-list .course-tab').count(),5);
 assert.equal(await page.evaluate(()=>window.qaPageSize),5);
 assert.equal(await page.locator('.library-actions button[aria-label$="삭제"]').count(),5);
 const pager=await page.locator('.saved-pagination').boundingBox();
 const panel=await page.locator('.course-sidebar').boundingBox();
 assert.ok(Math.abs(pager.x+pager.width/2-(panel.x+panel.width/2))<2);
 assert.equal(await page.locator('.fixed-tab .close-tab').count(),0);
 await page.screenshot({path:join(tmpdir(),'saved-list-tabs.png')});
 await page.locator('.library-list .course-tab').first().click();
 await page.locator('.stop-card').first().waitFor();
 assert.equal(await page.getByRole('button',{name:'코스 공유',exact:true}).isDisabled(),false);
 assert.equal(await page.locator('.course-actions button').count(),0);
 assert.equal(await page.locator('.stop-card .stop-photo').count(),3);
 assert.equal(await page.locator('.place-stop .stop-footer').count(),3);
 assert.deepEqual(await page.locator('.place-detail').evaluateAll(links=>links.map(link=>link.getAttribute('href'))),['/places/1','/places/2','/places/3'],'each detail link must target its own place');
 assert.match(await page.locator('.stop-card').first().innerText(),/집중률 24.0%/);
 assert.match(await page.locator('.stop-card').nth(1).innerText(),/8,000원/);
 assert.equal(await page.locator('.navi-action').count(),0);
 assert.match(await page.locator('.kakao-marker').last().getAttribute('aria-label'), /혼잡 정보 없음/);
 await page.screenshot({path:join(tmpdir(),'saved-desktop.png')});
 await page.locator('.fixed-tab').click();
 await page.locator('.library-list .course-tab').nth(1).click();
 assert.equal(await page.locator('.close-tab').count(),2);
 await page.locator('.close-tab').last().click();
 assert.equal(await page.locator('.close-tab').count(),1);
 assert.equal(await page.locator('.sheet-body').isVisible(),true);
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148'});
 const mobile=await context.newPage();await mobile.goto(url);
 await mobile.locator('.library-list .course-tab').first().click();
 await mobile.locator('.stop-card').first().waitFor();
 const mapBox=await mobile.locator('.saved-map').boundingBox();
 const browserBox=await mobile.locator('.course-browser').boundingBox();
 const sheetBox=await mobile.locator('.itinerary-sheet').boundingBox();
 assert.ok(mapBox.y>=browserBox.y+browserBox.height-1,'mobile map starts below course selector');
 assert.ok(mapBox.y+mapBox.height<=sheetBox.y+1,'map center must not hide behind sheet');
 await mobile.locator('.navi-action button').click();
 assert.equal((await mobile.evaluate(()=>window.qaNavi)).name,'금오름');
 await mobile.screenshot({path:join(tmpdir(),'saved-mobile.png')});
 const handle=mobile.locator('.sheet-handle'); const box=await handle.boundingBox();
 await mobile.mouse.move(box.x+box.width/2,box.y+15);await mobile.mouse.down();await mobile.mouse.move(box.x+box.width/2,box.y-130,{steps:8});await mobile.mouse.up();
 assert.ok(parseFloat(await mobile.locator('.saved-workspace').evaluate(el=>el.style.getPropertyValue('--sheet-height')))>55);
 await mobile.locator('.fixed-tab').click();
 await mobile.getByRole('button',{name:'다음 페이지',exact:true}).click();
 await mobile.waitForFunction(()=>document.querySelector('.saved-pagination').textContent.includes('2 / 2'));
 assert.equal(await mobile.locator('.library-list .course-tab').count(),3);
 await mobile.locator('.library-list .course-tab').first().click();
 assert.equal(await mobile.locator('.saved-workspace').evaluate(el=>el.style.getPropertyValue('--sheet-height')),'55%','paging must reopen sheet');
 await page.setViewportSize({width:900,height:800});await page.waitForTimeout(150);
 assert.ok(await page.evaluate(()=>window.qaMap.relayouts)>0,'map must relayout after resizing');
 await mobile.evaluate(()=>document.documentElement.dataset.theme='dark');
 await mobile.screenshot({path:join(tmpdir(),'saved-mobile-dark.png')});
 await mobile.setViewportSize({width:320,height:640});
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'narrow mobile must not overflow');
 await mobile.locator('.sheet-handle').focus();await mobile.keyboard.press('ArrowUp');
 assert.equal(await mobile.locator('.saved-workspace').evaluate(el=>el.style.getPropertyValue('--sheet-height')),'70%');
 await page.locator('.fixed-tab').click();
 page.once('dialog',dialog=>dialog.dismiss());
 await page.locator('.library-actions button[aria-label$="삭제"]').nth(1).click();
 assert.deepEqual(await page.evaluate(()=>window.qaDeleted),[],'cancel must not delete');
 page.once('dialog',dialog=>dialog.accept());
 await page.locator('.library-actions button[aria-label$="삭제"]').nth(1).click();
 await page.waitForFunction(()=>window.qaDeleted.length===1);
 assert.deepEqual(await page.evaluate(()=>window.qaDeleted),['2'],'delete must target the clicked list card');
 await browser.close();console.log('Saved course desktop/mobile UI checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
