// Run with a local Vite server; PLAYWRIGHT_MODULE optionally points to a shared installation.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const {join}=require('node:path');
const {tmpdir}=require('node:os');
const url=(process.env.SAVED_COURSES_TEST_URL || 'http://127.0.0.1:5208')+'/tests/browser/saved-courses.html'+(process.env.SAVED_COURSES_RENAMED ? '?variant=renamed' : '');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.goto(url);
 await page.locator('.library-list .course-tab').first().waitFor();
 assert.equal(await page.locator('.library-list .course-tab').count(),5);
 assert.equal(await page.evaluate(()=>window.qaPageSize),5);
 assert.equal(await page.getByRole('button',{name:/ 메뉴$/}).count(),5);
 const firstCard=page.locator('.library-card').first();
 await firstCard.getByRole('button',{name:/ 메뉴$/}).click();
 assert.deepEqual(await page.getByRole('menuitem').allTextContents(),['이름 변경','공유','삭제']);
 await page.getByRole('menuitem',{name:'이름 변경'}).click();
 const renamedTitle='이름 변경 검증 코스';
 await page.getByLabel('코스 이름',{exact:true}).fill(renamedTitle);
 await page.locator('.course-rename-dialog').getByRole('button',{name:'저장',exact:true}).click();
 await firstCard.getByRole('button',{name:`${renamedTitle} 메뉴`,exact:true}).waitFor();
 const pager=await page.locator('.saved-pagination').boundingBox();
 const panel=await page.locator('.course-sidebar').boundingBox();
 assert.ok(Math.abs(pager.x+pager.width/2-(panel.x+panel.width/2))<2);
 assert.equal(await page.locator('.fixed-tab .close-tab').count(),0);
 await page.screenshot({path:join(tmpdir(),'saved-list-tabs.png')});
 await page.locator('.library-list .course-tab').first().click();
 await page.locator('.stop-card').first().waitFor();
 assert.equal(await page.getByRole('button',{name:'코스 공유',exact:true}).isDisabled(),false);
 assert.equal(await page.getByRole('button',{name:'주소 복사',exact:true}).count(),0);
 assert.equal(await page.locator('.course-actions button').count(),0);
 assert.equal(await page.locator('.stop-card .stop-photo').count(),3);
 assert.equal(await page.locator('.place-stop .stop-footer').count(),3);
 assert.deepEqual(await page.locator('.place-detail').evaluateAll(links=>links.map(link=>link.getAttribute('href'))),['/places/1','/places/2','/places/3'],'each detail link must target its own place');
 assert.doesNotMatch(await page.locator('.stop-card').first().innerText(),/집중률/);
 assert.equal(await page.locator('.stop-card').first().locator('.crowd-pill').innerText(),'한산');
 assert.match(await page.locator('.stop-card').nth(1).innerText(),/8,000원/);
 assert.doesNotMatch(await page.locator('.sheet-body').innerText(),/체류/);
 for (const theme of ['dark','light']) {
  await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.stop-card .price-pill')).backgroundColor==='rgb(251, 227, 237)');
 }
 assert.equal(await page.locator('.navi-action').count(),0);
 assert.equal(await page.locator('.map-caption').count(),0);
 await page.getByRole('button',{name:'DAY 1 일정 수정',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:/대안 보기$/}).count(),3);
 // 장소명이 아니라 편집 중인 일차와 방문 순서로 범위를 좁힌다.
 // 아래 요청 ID 단언은 잘못된 장소의 버튼을 누르는 회귀도 잡는다.
 const firstStop=page.locator('.itinerary-day').first().locator('.place-stop').first();
 await firstStop.getByRole('button',{name:/ 대안 보기$/}).click();
 const alternativeName=await page.locator('.alt-list article h3').first().innerText();
 assert.equal(await page.locator('.alt-list article').count(),3);
 assert.match(await page.locator('.alternative-header').innerText(),/직선거리 20km/);
 assert.equal(await page.locator('.alternative-map').first().getAttribute('href'),'/map?place=99');
 await page.getByRole('button',{name:'이곳으로 변경'}).first().click();
 await page.waitForFunction(name=>document.querySelector('.stop-card')?.textContent.includes(name),alternativeName);
 assert.deepEqual(await page.evaluate(()=>window.qaSwaps),[{id:'1',itemId:10,placeId:99}]);
 assert.equal(await page.getByRole('button',{name:'DAY 1 수정 완료',exact:true}).count(),1);
 async function assertTripBackground(expected) {
  await page.waitForFunction(expected=>{
   const button=document.querySelector('.trip-icon');
   if(!button) return false;
   return getComputedStyle(button).backgroundColor===expected && getComputedStyle(button).color!==expected;
  },expected);
 }
 await assertTripBackground('rgb(226, 243, 223)');
 await page.evaluate(()=>document.documentElement.dataset.theme='dark');
 await assertTripBackground('rgb(226, 243, 223)');
 await page.evaluate(()=>document.documentElement.dataset.theme='light');
 await page.getByRole('button',{name:'여행 확정',exact:true}).click();
 await page.getByRole('button',{name:'확정하기',exact:true}).click();
 await assertTripBackground('rgb(251, 227, 229)');
 await page.evaluate(()=>document.documentElement.dataset.theme='dark');
 await assertTripBackground('rgb(251, 227, 229)');
 await page.evaluate(()=>document.documentElement.dataset.theme='light');
 await page.getByRole('button',{name:'여행 확정 취소',exact:true}).click();
 await page.getByRole('button',{name:'확정 취소',exact:true}).click();
 await page.getByRole('button',{name:'여행 확정',exact:true}).waitFor();
 assert.match(await page.locator('.kakao-marker').last().getAttribute('aria-label'), /혼잡 정보 없음/);
 await page.screenshot({path:join(tmpdir(),'saved-desktop.png')});
 await page.locator('.fixed-tab').click();
 await page.locator('.library-list .course-tab').nth(1).click();
 assert.equal(await page.locator('.close-tab').count(),2);
 await page.locator('.close-tab').last().click();
 assert.equal(await page.locator('.close-tab').count(),1);
 assert.equal(await page.locator('.sheet-body').isVisible(),true);
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148'});
 const mobile=await context.newPage();await mobile.goto(url);
 await mobile.locator('.library-list .course-tab').first().click();
 await mobile.locator('.stop-card').first().waitFor();
 const mapBox=await mobile.locator('.saved-map').boundingBox();
 const browserBox=await mobile.locator('.course-browser').boundingBox();
 const sheetBox=await mobile.locator('.itinerary-sheet').boundingBox();
 assert.ok(mapBox.y>=browserBox.y+browserBox.height-1,'mobile map starts below course selector');
 assert.ok(mapBox.y+mapBox.height<=sheetBox.y+1,'map center must not hide behind sheet');
 const destinationName=await mobile.locator('.stop-copy>strong').first().innerText();
 await mobile.locator('.navi-action button').click();
 assert.equal((await mobile.evaluate(()=>window.qaNavi)).name,destinationName);
 await mobile.screenshot({path:join(tmpdir(),'saved-mobile.png')});
 const handle=mobile.locator('.sheet-handle'); const box=await handle.boundingBox();
 await mobile.mouse.move(box.x+box.width/2,box.y+15);await mobile.mouse.down();await mobile.mouse.move(box.x+box.width/2,box.y-130,{steps:8});await mobile.mouse.up();
 assert.ok(parseFloat(await mobile.locator('.saved-workspace').evaluate(el=>el.style.getPropertyValue('--sheet-height')))>55);
 await handle.press('End');
 await mobile.waitForFunction(()=>{
  const header=document.querySelector('.course-browser').getBoundingClientRect();
  const sheet=document.querySelector('.itinerary-sheet').getBoundingClientRect();
  return !document.querySelector('.itinerary-sheet').getAnimations().some(a=>a.playState==='running') && Math.abs(sheet.top-header.bottom)<2;
 });
 await mobile.locator('.fixed-tab').click();
 await mobile.getByRole('button',{name:'다음 페이지',exact:true}).click();
 await mobile.waitForFunction(()=>document.querySelector('.saved-pagination').textContent.includes('2 / 2'));
 assert.equal(await mobile.locator('.library-list .course-tab').count(),3);
 await mobile.locator('.library-list .course-tab').first().click();
 assert.equal(await mobile.locator('.saved-workspace').evaluate(el=>el.style.getPropertyValue('--sheet-height')),'55%','paging must reopen sheet');
 await page.setViewportSize({width:900,height:800});await page.waitForTimeout(150);
 assert.ok(await page.evaluate(()=>window.qaMap.relayouts)>0,'map must relayout after resizing');
 await mobile.evaluate(()=>document.documentElement.dataset.theme='dark');
 await mobile.screenshot({path:join(tmpdir(),'saved-mobile-dark.png')});
 await mobile.setViewportSize({width:320,height:640});
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'narrow mobile must not overflow');
 await mobile.locator('.sheet-handle').focus();await mobile.keyboard.press('ArrowUp');
 assert.equal(await mobile.locator('.saved-workspace').evaluate(el=>el.style.getPropertyValue('--sheet-height')),'70%');
 await page.locator('.fixed-tab').click();
 page.once('dialog',dialog=>dialog.dismiss());
 await page.locator('.library-card').nth(1).getByRole('button',{name:/ 메뉴$/}).click();
 await page.getByRole('menuitem',{name:'삭제',exact:true}).click();
 assert.deepEqual(await page.evaluate(()=>window.qaDeleted),[],'cancel must not delete');
 page.once('dialog',dialog=>dialog.accept());
 await page.locator('.library-card').nth(1).getByRole('button',{name:/ 메뉴$/}).click();
 await page.getByRole('menuitem',{name:'삭제',exact:true}).click();
 await page.waitForFunction(()=>window.qaDeleted.length===1);
 assert.deepEqual(await page.evaluate(()=>window.qaDeleted),['2'],'delete must target the clicked list card');
 // Real router + real CourseService: legacy URLs now render the unified screen.
 const actual=await browser.newPage();
 await actual.route('**/auth/reissue',r=>r.fulfill({status:401,json:{success:false,code:3002,message:'guest'}}));
 await actual.route('**/courses/42',r=>r.request().resourceType()==='document'?r.continue():r.fulfill({json:{success:true,result:{id:42,title:'공개 코스 경로 검증',transport:'RENTAL_CAR',duration_text:'당일',people:2,start_date:'2026-09-20',end_date:'2026-09-20',status:'SAMPLE',swappable:false,manageable:false,days:[{day_no:1,visit_date:'2026-09-20',items:[]}]}}}));
 const origin=process.env.SAVED_COURSES_TEST_URL || 'http://127.0.0.1:5208';
 await actual.goto(origin+'/courses/42');
 await actual.locator('.course-actions').getByText('공개 코스 경로 검증',{exact:true}).waitFor();
 assert.equal(await actual.locator('.saved-workspace').count(),1);
 assert.equal(await actual.locator('.day-edit').count(),0,'public read-only course has no edit controls');
 assert.equal(await actual.getByRole('button',{name:'코스 공유',exact:true}).isDisabled(),true);
 await actual.reload();
 await actual.locator('.course-actions').getByText('공개 코스 경로 검증',{exact:true}).waitFor();
 await actual.route('**/courses/404',r=>r.request().resourceType()==='document'?r.continue():r.fulfill({status:404,json:{success:false,code:3301,message:'not found'}}));
 await actual.goto(origin+'/courses/404');
 await actual.getByRole('alert').filter({hasText:'일정을 불러오지 못했어요.'}).waitFor();
 assert.equal(await actual.locator('.stop-card').count(),0,'failed detail must not show a fake course');
 await actual.close();
 await browser.close();console.log('Saved course desktop/mobile UI checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
